dist: trusty
language: d
d:
  - dmd
  - ldc

before_script: git fetch --unshallow
script: dub --config=test --compiler=${DC}

os:
  - linux
  - osx

env:
  - LLVM_VERSION=4.0.0
  - LLVM_VERSION=3.9.1
  - LLVM_VERSION=3.9.0

matrix:
  # beta and nightly builds for DMD and LDC
  include:
    - &entry
      d: dmd-beta
      os: linux
      env: LLVM_VERSION=4.0.0
    - <<: *entry
      d: ldc-beta
    - <<: *entry
      d: dmd-nightly
  allow_failures:
    - <<: *entry
      d: dmd-nightly

  # missing binaries from http://releases.llvm.org
  exclude:
    - env: LLVM_VERSION=3.9.1
      os: osx
