dist: xenial
language: d
d:
  - dmd
  - ldc

install: |
  [ -z ${TRAVIS_TAG} ] && extra_flags='' || extra_flags='--dstep'
  ./tools/download_llvm.d $extra_flags

before_script:
  - git fetch --unshallow
  - ./configure --llvm-path tmp/clang

script: dub test --verror --compiler=${DC}

os:
  - linux
  - osx

env:
  global: MACOSX_DEPLOYMENT_TARGET=10.9
  matrix:
    - LLVM_VERSION=8.0.0
    - LLVM_VERSION=7.0.0
    # Used by Sociomantic
    - LLVM_VERSION=6.0.0

matrix:
  include:
    # beta and nightly builds for DMD and LDC
    - &entry
      d: dmd-beta
      os: linux
      env: LLVM_VERSION=8.0.0
    - <<: *entry
      d: ldc-beta
    - <<: *entry
      d: dmd-nightly

    # deployment
    - &deploy
      stage: deploy
      if: tag IS present
      d: ldc
      os: linux
      env: LLVM_VERSION=8.0.0
      script: ./tools/build_release.sh
      deploy:
        provider: releases
        api_key:
          secure: ABIe03HKvDC29vq9iwjNR2CdVzR+hwb987xQ00TaeuiBzcqAWagdNgKT2Flkqmsce0ppDN6XcMQqvJ7oi5fEkJ3rJB/Amws7dKzxglZKHDqHqskL6RzVpNIOvbcN0hv/FuQm+w4ha5/VbzMrGtYgYXCZYQQeT12pNrKZSuUoGEE=
        draft: true
        tag_name: $TRAVIS_TAG
        file_glob: true
        file: dstep*.tar.xz
        skip_cleanup: true
        on:
          tags: true
    - <<: *deploy
      os: osx
      before_install: brew install ncurses

  allow_failures:
    - <<: *entry
      d: dmd-nightly
