platform:
  - x64
  - x86

configuration:
  - LLVM 4.0.0
  - LLVM 3.9.1
  - LLVM 3.9.0

environment:
  DVersion: 2.071.0
  DC: dmd

skip_tags: true

install:
  - echo dummy install script - dont remove me

build_script:
  - echo dummy build script - dont remove me

test_script:
  - powershell -NoProfile -File appveyor.ps1 < NUL
